// Base de dados de dispositivos para cadastro inteligente

export interface BrandData {
  name: string;
  category: string;
  os: string;
  models: string[];
}

export const BRANDS: BrandData[] = [
  {
    name: "Apple",
    category: "Smartphone",
    os: "iOS",
    models: [
      "iPhone SE (2ª geração)",
      "iPhone SE (3ª geração)",
      "iPhone 11",
      "iPhone 11 Pro",
      "iPhone 11 Pro Max",
      "iPhone 12",
      "iPhone 12 Mini",
      "iPhone 12 Pro",
      "iPhone 12 Pro Max",
      "iPhone 13",
      "iPhone 13 Mini",
      "iPhone 13 Pro",
      "iPhone 13 Pro Max",
      "iPhone 14",
      "iPhone 14 Plus",
      "iPhone 14 Pro",
      "iPhone 14 Pro Max",
      "iPhone 15",
      "iPhone 15 Plus",
      "iPhone 15 Pro",
      "iPhone 15 Pro Max",
      "iPhone 16",
      "iPhone 16 Plus",
      "iPhone 16 Pro",
      "iPhone 16 Pro Max",
      "iPad (9ª geração)",
      "iPad (10ª geração)",
      "iPad Mini (6ª geração)",
      "iPad Air (5ª geração)",
      "iPad Air M2",
      "iPad Air M3",
      'iPad Pro 11"',
      'iPad Pro 13"',
      "Apple Watch Series 8",
      "Apple Watch Series 9",
      "Apple Watch Series 10",
      "Apple Watch Ultra",
      "Apple Watch Ultra 2",
      "AirPods (3ª geração)",
      "AirPods Pro (2ª geração)",
      "AirPods Max",
      "MacBook Air M1",
      "MacBook Air M2",
      "MacBook Air M3",
      'MacBook Pro 14" M3',
      'MacBook Pro 16" M3',
    ],
  },
  {
    name: "Samsung",
    category: "Smartphone",
    os: "Android",
    models: [
      "Galaxy A04",
      "Galaxy A04s",
      "Galaxy A05",
      "Galaxy A05s",
      "Galaxy A14",
      "Galaxy A14 5G",
      "Galaxy A15",
      "Galaxy A15 5G",
      "Galaxy A24",
      "Galaxy A25 5G",
      "Galaxy A34 5G",
      "Galaxy A35 5G",
      "Galaxy A54 5G",
      "Galaxy A55 5G",
      "Galaxy M14",
      "Galaxy M14 5G",
      "Galaxy M34 5G",
      "Galaxy M55 5G",
      "Galaxy S21",
      "Galaxy S21+",
      "Galaxy S21 Ultra",
      "Galaxy S22",
      "Galaxy S22+",
      "Galaxy S22 Ultra",
      "Galaxy S23",
      "Galaxy S23+",
      "Galaxy S23 Ultra",
      "Galaxy S24",
      "Galaxy S24+",
      "Galaxy S24 Ultra",
      "Galaxy S24 FE",
      "Galaxy S25",
      "Galaxy S25+",
      "Galaxy S25 Ultra",
      "Galaxy Z Flip4",
      "Galaxy Z Flip5",
      "Galaxy Z Flip6",
      "Galaxy Z Fold4",
      "Galaxy Z Fold5",
      "Galaxy Z Fold6",
      "Galaxy Tab A8",
      "Galaxy Tab A9",
      "Galaxy Tab A9+",
      "Galaxy Tab S8",
      "Galaxy Tab S9",
      "Galaxy Tab S9+",
      "Galaxy Tab S9 Ultra",
    ],
  },
  {
    name: "Motorola",
    category: "Smartphone",
    os: "Android",
    models: [
      "Moto E13",
      "Moto E14",
      "Moto E22",
      "Moto E32",
      "Moto G04",
      "Moto G04s",
      "Moto G14",
      "Moto G24",
      "Moto G24 Power",
      "Moto G34 5G",
      "Moto G54 5G",
      "Moto G62 5G",
      "Moto G73 5G",
      "Moto G84",
      "Moto G85",
      "Moto G100",
      "Edge 30",
      "Edge 30 Neo",
      "Edge 30 Pro",
      "Edge 30 Ultra",
      "Edge 40",
      "Edge 40 Neo",
      "Edge 40 Pro",
      "Edge 50 Pro",
      "Edge 50 Ultra",
      "Edge 50 Fusion",
      "Razr 40",
      "Razr 40 Ultra",
      "Razr 50",
      "Razr 50 Ultra",
    ],
  },
  {
    name: "Xiaomi",
    category: "Smartphone",
    os: "Android",
    models: [
      "Xiaomi 12",
      "Xiaomi 12 Pro",
      "Xiaomi 12X",
      "Xiaomi 12 Lite",
      "Xiaomi 12S Ultra",
      "Xiaomi 13",
      "Xiaomi 13 Pro",
      "Xiaomi 13 Ultra",
      "Xiaomi 13T",
      "Xiaomi 13T Pro",
      "Xiaomi 14",
      "Xiaomi 14 Pro",
      "Xiaomi 14 Ultra",
      "Xiaomi 14T",
      "Xiaomi 14T Pro",
    ],
  },
  {
    name: "Redmi",
    category: "Smartphone",
    os: "Android",
    models: [
      "Redmi 10",
      "Redmi 10C",
      "Redmi 12",
      "Redmi 12C",
      "Redmi 13",
      "Redmi 13C",
      "Redmi Note 11",
      "Redmi Note 11 Pro",
      "Redmi Note 11S",
      "Redmi Note 12",
      "Redmi Note 12 Pro",
      "Redmi Note 12 Pro+",
      "Redmi Note 12S",
      "Redmi Note 13",
      "Redmi Note 13 Pro",
      "Redmi Note 13 Pro+",
      "Redmi Note 13 4G",
      "Redmi Note 14",
      "Redmi Note 14 Pro",
      "Redmi Note 14 Pro+",
    ],
  },
  {
    name: "Poco",
    category: "Smartphone",
    os: "Android",
    models: [
      "Poco C40",
      "Poco C55",
      "Poco C65",
      "Poco M4 Pro",
      "Poco M5",
      "Poco M5s",
      "Poco M6",
      "Poco M6 Pro",
      "Poco X4 GT",
      "Poco X4 Pro",
      "Poco X5",
      "Poco X5 Pro",
      "Poco X6",
      "Poco X6 Pro",
      "Poco F4",
      "Poco F4 GT",
      "Poco F5",
      "Poco F5 Pro",
      "Poco F6",
      "Poco F6 Pro",
    ],
  },
  {
    name: "Realme",
    category: "Smartphone",
    os: "Android",
    models: [
      "Realme C30",
      "Realme C33",
      "Realme C53",
      "Realme C55",
      "Realme C67",
      "Realme 10",
      "Realme 11",
      "Realme 11 Pro",
      "Realme 11 Pro+",
      "Realme 12",
      "Realme 12+",
      "Realme 12 Pro",
      "Realme 12 Pro+",
      "Realme GT Neo 3",
      "Realme GT Neo 5",
      "Realme GT 6",
      "Realme GT 6T",
    ],
  },
  {
    name: "Asus",
    category: "Smartphone",
    os: "Android",
    models: [
      "Zenfone 9",
      "Zenfone 10",
      "Zenfone 11 Ultra",
      "ROG Phone 6",
      "ROG Phone 6 Pro",
      "ROG Phone 7",
      "ROG Phone 7 Pro",
      "ROG Phone 8",
      "ROG Phone 8 Pro",
    ],
  },
  {
    name: "Oppo",
    category: "Smartphone",
    os: "Android",
    models: [
      "Oppo A18",
      "Oppo A38",
      "Oppo A58",
      "Oppo A78",
      "Oppo A98",
      "Oppo Find X6",
      "Oppo Find X7",
      "Oppo Find X7 Pro",
      "Oppo Reno 10",
      "Oppo Reno 10 Pro",
      "Oppo Reno 11",
      "Oppo Reno 11 Pro",
      "Oppo Reno 12",
      "Oppo Reno 12 Pro",
    ],
  },
  {
    name: "Vivo",
    category: "Smartphone",
    os: "Android",
    models: [
      "Vivo Y02",
      "Vivo Y16",
      "Vivo Y17s",
      "Vivo Y22s",
      "Vivo Y27",
      "Vivo Y27s",
      "Vivo Y36",
      "Vivo V25",
      "Vivo V27",
      "Vivo V29",
      "Vivo V30",
      "Vivo V40",
      "Vivo V40 Pro",
      "Vivo X90",
      "Vivo X100",
      "Vivo X200",
      "Vivo X200 Pro",
    ],
  },
  {
    name: "Honor",
    category: "Smartphone",
    os: "Android",
    models: [
      "Honor X6",
      "Honor X6a",
      "Honor X7",
      "Honor X7a",
      "Honor X8",
      "Honor X8a",
      "Honor X9a",
      "Honor X9b",
      "Honor 90",
      "Honor 90 Lite",
      "Honor 200",
      "Honor 200 Pro",
      "Honor Magic5 Lite",
      "Honor Magic6",
      "Honor Magic6 Pro",
      "Honor Magic6 Ultimate",
    ],
  },
  {
    name: "Huawei",
    category: "Smartphone",
    os: "HarmonyOS",
    models: [
      "Huawei Nova 11",
      "Huawei Nova 11 Pro",
      "Huawei Nova 12",
      "Huawei Nova 12 Pro",
      "Huawei P50",
      "Huawei P50 Pro",
      "Huawei P60 Pro",
      "Huawei Mate 50",
      "Huawei Mate 50 Pro",
      "Huawei Mate 60",
      "Huawei Mate 60 Pro",
    ],
  },
  {
    name: "Nokia",
    category: "Smartphone",
    os: "Android",
    models: [
      "Nokia G21",
      "Nokia G22",
      "Nokia G42",
      "Nokia G60",
      "Nokia XR21",
      "Nokia C32",
      "Nokia C300",
    ],
  },
  {
    name: "LG",
    category: "Smartphone",
    os: "Android",
    models: [
      "LG K62",
      "LG K92 5G",
      "LG Velvet",
      "LG Wing",
      "LG V60 ThinQ",
    ],
  },
  {
    name: "Sony",
    category: "Smartphone",
    os: "Android",
    models: [
      "Xperia 1 IV",
      "Xperia 5 IV",
      "Xperia 10 IV",
      "Xperia 1 V",
      "Xperia 5 V",
      "Xperia 10 V",
      "Xperia 1 VI",
      "Xperia 10 VI",
    ],
  },
  {
    name: "Google",
    category: "Smartphone",
    os: "Android",
    models: [
      "Pixel 6",
      "Pixel 6 Pro",
      "Pixel 6a",
      "Pixel 7",
      "Pixel 7 Pro",
      "Pixel 7a",
      "Pixel 8",
      "Pixel 8 Pro",
      "Pixel 8a",
      "Pixel 9",
      "Pixel 9 Pro",
      "Pixel 9 Pro XL",
      "Pixel 9 Pro Fold",
      "Pixel Fold",
    ],
  },
  {
    name: "Infinix",
    category: "Smartphone",
    os: "Android",
    models: [
      "Infinix Hot 20",
      "Infinix Hot 20i",
      "Infinix Hot 30",
      "Infinix Hot 30i",
      "Infinix Hot 40",
      "Infinix Hot 40i",
      "Infinix Note 30",
      "Infinix Note 30 Pro",
      "Infinix Note 40",
      "Infinix Note 40 Pro",
      "Infinix Smart 7",
      "Infinix Smart 8",
      "Infinix Zero 30",
    ],
  },
  {
    name: "Tecno",
    category: "Smartphone",
    os: "Android",
    models: [
      "Tecno Spark 10",
      "Tecno Spark 10 Pro",
      "Tecno Spark 20",
      "Tecno Spark 20 Pro",
      "Tecno Pop 7",
      "Tecno Pop 8",
      "Tecno Camon 20",
      "Tecno Camon 20 Pro",
      "Tecno Phantom X2",
      "Tecno Phantom V Fold",
    ],
  },
  {
    name: "Outra",
    category: "Smartphone",
    os: "Outro",
    models: [],
  },
];

export const BRAND_NAMES: string[] = BRANDS.map((b) => b.name);

export const getBrandData = (brandName: string): BrandData | undefined =>
  BRANDS.find((b) => b.name === brandName);

export const getModels = (brandName: string): string[] =>
  getBrandData(brandName)?.models ?? [];

export const COLORS: string[] = [
  "Preto",
  "Branco",
  "Azul",
  "Vermelho",
  "Verde",
  "Roxo",
  "Dourado",
  "Prata",
  "Rosa",
  "Grafite",
  "Laranja",
  "Amarelo",
  "Ciano",
  "Coral",
  "Bege",
  "Marrom",
  "Titânio Natural",
  "Titânio Preto",
  "Titânio Branco",
  "Titânio Azul",
  "Midnight",
  "Starlight",
  "Product Red",
  "Desert Titanium",
  "Outra",
];

export const STORAGE_OPTIONS: string[] = [
  "32GB",
  "64GB",
  "128GB",
  "256GB",
  "512GB",
  "1TB",
  "2TB",
  "Outro",
];

export const RAM_OPTIONS: string[] = [
  "2 GB",
  "3 GB",
  "4 GB",
  "6 GB",
  "8 GB",
  "12 GB",
  "16 GB",
  "Outro",
];

export const CONDITIONS: string[] = [
  "Novo",
  "Seminovo",
  "Excelente",
  "Bom",
  "Regular",
  "Ruim",
];
